'use client'
import { useMemo, useState } from 'react'
import { usePathname } from 'next/navigation'
import { AppShell, card } from './AppShell'
import { auditLogs, kpiByRole, maintenanceRequests, notifications } from '@/data/mockData'

const badgeCls = (t: string) => t.includes('Breach') || t.includes('Critical') || t.includes('Cannot') || t.includes('Rejected') ? 'bg-red-100 text-red-700' : t.includes('High') || t.includes('Progress') || t.includes('Warning') ? 'bg-amber-100 text-amber-700' : t.includes('Closed') || t.includes('Verified') || t.includes('Complete') || t.includes('Success') || t.includes('Connected') ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'
const Badge = ({ text }: { text: string }) => <span className={`rounded-full px-2 py-1 text-xs font-semibold ${badgeCls(text)}`}>{text}</span>
const KPI = ({ label, value }: { label: string; value: string }) => <div className={card}><p className='text-xs uppercase text-slate-500'>{label}</p><p className='mt-2 text-4xl font-bold text-[#0B4EDB]'>{value}</p></div>

const FeatureTable = ({ title, cols, rows }: { title: string; cols: string[]; rows: (string | JSX.Element)[][] }) => <div className={card}><h3 className='mb-4 text-2xl font-semibold'>{title}</h3><table className='w-full text-sm'><thead><tr className='border-b text-left text-slate-500'>{cols.map(c => <th className='py-2' key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i} className='border-b align-top'>{r.map((c, j) => <td className='py-3 pr-3' key={j}>{c}</td>)}</tr>)}</tbody></table></div>

const UploadBox = ({ title }: { title: string }) => <div className='rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-6 text-center'><p className='font-semibold'>{title}</p><p className='text-sm text-slate-500'>PNG/JPG, max 5MB</p><button className='mt-3 rounded-xl bg-[#0B4EDB] px-4 py-2 text-white'>Upload</button></div>

export function RoleDashboard({ role, title, subtitle }: { role: any; title: string; subtitle: string }) {
  const kpis = (kpiByRole as any)[role] || []
  return <AppShell role={role} title={title}><div className='mb-6'><h1 className='text-5xl font-bold'>{title}</h1><p className='text-slate-600'>{subtitle}</p></div><div className='grid gap-4 md:grid-cols-2 xl:grid-cols-4'>{kpis.map((k: any) => <KPI key={k.label} label={k.label} value={k.value} />)}</div><div className='mt-6 grid gap-5 xl:grid-cols-3'><div className='xl:col-span-2'><FeatureTable title='Recent Requests Needing Attention' cols={['ID', 'Request', 'Building', 'Status', 'Priority', 'SLA']} rows={maintenanceRequests.map(r => [r.id, <>{r.title}<div className='text-slate-500'>{r.tenant}</div></>, `${r.building} / ${r.unit}`, <Badge text={r.status} />, <Badge text={r.priority} />, r.sla])} /></div><div className='space-y-5'><div className={card}><h3 className='mb-3 text-xl font-semibold'>Notifications</h3>{notifications.map(n => <div key={n.id} className='mb-2 rounded-lg bg-slate-50 p-2 text-sm flex justify-between'><span>{n.title}</span><Badge text={n.channel} /></div>)}</div><div className={card}><h3 className='mb-3 text-xl font-semibold'>System Audit Log</h3>{auditLogs.map(a => <div key={a.ts + a.action} className='mb-2 rounded-lg bg-slate-50 p-2 text-sm'><p className='font-medium'>{a.action}</p><p className='text-slate-500'>{a.actor} · {a.ts}</p></div>)}</div></div></div></AppShell>
}

export function ListPage({ role }: { role: any; title: string }) {
  const path = usePathname()
  const [note, setNote] = useState('')
  const page = useMemo(() => {
    if (path === '/admin/users') return <div className='space-y-5'><h1 className='text-3xl font-bold'>User Management</h1><div className='grid gap-4 md:grid-cols-4'><KPI label='Total Users' value='450' /><KPI label='Active Users' value='422' /><KPI label='Pending Users' value='12' /><KPI label='Deactivated Users' value='16' /></div><div className={`${card} flex flex-wrap gap-2`}><input className='rounded-xl border px-3 py-2' placeholder='Search user' /><select className='rounded-xl border px-3 py-2'><option>Role</option></select><select className='rounded-xl border px-3 py-2'><option>Status</option></select><select className='rounded-xl border px-3 py-2'><option>Building</option></select><button className='ml-auto rounded-xl bg-[#0B4EDB] px-4 py-2 text-white'>Create User</button></div><FeatureTable title='Users' cols={['User','Role','Assigned Scope','Status','Last Login','Actions']} rows={[['Sarah Miller','Property Manager','Skyline Tower, Oak Terrace',<Badge text='Active'/>, '2026-05-21 08:12','Edit · Deactivate · Reset Password'],['Marcus Lee','Technician','Green Valley · HVAC',<Badge text='Pending'/>, 'Never','Edit · Activate']]} /></div>
    if (path === '/admin/tenant-approvals') return <div className='space-y-5'><h1 className='text-3xl font-bold'>Tenant Approval Queue</h1><FeatureTable title='Pending Registrations' cols={['Tenant Name','Phone','Email','Requested Building','Requested Unit','Submitted Date','Status','Actions']} rows={[['Lina Park','+1 555 802 1112','lina.park@email.com','Skyline Tower','14B','2026-05-20',<Badge text='Pending'/>, 'Approve · Reject (reason required)'],['Noah Reed','+1 555 993 7744','noahr@site.com','Oak Terrace','11C (mismatch)', '2026-05-19',<Badge text='Warning'/>, <span className='text-red-600'>Unit mismatch warning</span>]]} /><div className={card}><h3 className='text-xl font-semibold'>Approval History</h3><p className='text-sm text-slate-600 mt-2'>2026-05-21 · Sarah Miller approved 5 tenants. Rejections require reason and are logged.</p></div></div>
    if (path === '/admin/sla-settings') return <div className='space-y-5'><h1 className='text-3xl font-bold'>SLA Settings</h1><p className='text-slate-600'>Configure response and resolution targets by priority and category.</p><div className='grid gap-4 md:grid-cols-4'><KPI label='Active SLA Rules' value='12' /><KPI label='Critical Breach Rate' value='3.8%' /><KPI label='Average Response Target' value='3.8h' /><KPI label='Average Resolution Target' value='38h' /></div><FeatureTable title='SLA Rules' cols={['Priority','Response SLA','Resolution SLA','Applies To Categories','Calendar Mode','Escalation Rule','Status','Actions']} rows={[['Critical','1h','8h','Plumbing, Elevator','24/7','Escalate to on-call PM (15m)',<Badge text='Active'/>, 'Edit · Deactivate'],['High','2h','24h','Electrical, HVAC','Business + after-hours','Escalate to PM (30m)',<Badge text='Active'/>, 'Edit'],['Medium','4h','48h','General Maintenance','Business hours','Email reminder',<Badge text='Active'/>, 'Edit'],['Low','8h','72h','Cleaning','Business hours','None',<Badge text='Pending Client Decision'/>, 'Activate']]}/><div className='grid gap-4 lg:grid-cols-2'><div className={card}><h3 className='text-xl font-semibold'>SLA Behavior Settings</h3><ul className='mt-3 list-disc pl-5 text-sm text-slate-700'><li>Response start: New / stop: Assigned</li><li>Resolution start: New / stop: Verified</li><li>Pause during Cancellation Requested</li><li>Continue with flag during Cannot Complete</li><li>Reset on Reopen</li></ul></div><div className={card}><h3 className='text-xl font-semibold'>Category SLA Mapping</h3><div className='mt-3 flex flex-wrap gap-2'>{['Plumbing','Electrical','HVAC','Elevator','General Maintenance'].map(c=><Badge key={c} text={c}/>)}</div><button className='mt-4 rounded-xl bg-[#0B4EDB] px-4 py-2 text-white'>Save Changes</button></div></div></div>
    if (path === '/admin/white-label') return <div className='space-y-5'><h1 className='text-3xl font-bold'>White Label Settings</h1><div className='grid gap-4 lg:grid-cols-2'><div className={card}><div className='grid gap-3 md:grid-cols-2'><UploadBox title='Logo Upload'/><UploadBox title='Favicon Upload'/></div><div className='mt-3 grid gap-3 md:grid-cols-2'><input className='rounded-xl border px-3 py-2' defaultValue='Maintenance Pro' /><input className='rounded-xl border px-3 py-2' defaultValue='portal.maintpro.com' /><input className='rounded-xl border px-3 py-2' defaultValue='#0B4EDB' /><input className='rounded-xl border px-3 py-2' defaultValue='#0F172A' /></div><div className='mt-4 flex gap-2'><button className='rounded-xl border px-4 py-2'>Preview</button><button className='rounded-xl bg-[#0B4EDB] px-4 py-2 text-white'>Save</button><button className='rounded-xl bg-emerald-600 px-4 py-2 text-white'>Publish</button><button className='rounded-xl border px-4 py-2'>Revert</button></div></div><div className={card}><h3 className='text-xl font-semibold'>Live Preview</h3><div className='mt-3 rounded-xl bg-[#0B4EDB] p-4 text-white'>Login, email, and report branding preview for custom domain.</div></div></div></div>
    if (path === '/pm/verification') return <FeatureTable title='Completed Work Verification' cols={['Request','Before Photo','After Photo','Technician Notes','Duration','SLA','Actions']} rows={[['WO-9001','Available','Missing', 'Leak fixed, valve changed','1h 42m',<Badge text='On Track'/>,'Verify and Close · Reject Verification · Request More Info'],['WO-9002','Available','Available', 'Filter replaced','45m',<Badge text='Breached'/>,'Verify and Close']]} />
    if (path === '/pm/sla-breaches') return <div className='space-y-4'><h1 className='text-3xl font-bold'>SLA Breaches</h1><div className='grid gap-4 md:grid-cols-3'><KPI label='Open Breaches' value='11' /><KPI label='Critical Breaches' value='3' /><KPI label='Avg Overdue' value='2.1h' /></div><FeatureTable title='Breach Queue' cols={['Request','Tenant','Building/Unit','Priority','Breach Type','Overdue Duration','Technician','Action']} rows={[['WO-9201','Marcus V','Skyline/14B',<Badge text='Critical'/>,'Resolution','2h 14m','John D','Escalate'],['WO-9203','Sarah L','Green/402',<Badge text='High'/>,'Response','48m','Ari K','Notify PM']]} /></div>
    if (path === '/tech/upload-before') return <div className={card}><h1 className='text-3xl font-bold'>Before Photo Upload</h1><UploadBox title='Camera / Upload Area'/><div className='mt-3 text-sm text-slate-600'>Required before completion. Accepted: JPG/PNG up to 5MB.</div><div className='mt-4 flex gap-2'><button className='rounded-xl border px-4 py-2'>Retake</button><button className='rounded-xl bg-[#0B4EDB] px-4 py-2 text-white'>Save</button></div></div>
    if (path === '/tech/complete') return <div className={card}><h1 className='text-3xl font-bold'>Complete Task</h1><p className='mt-2 text-sm'>Completion checklist</p><div className='mt-3 space-y-2'><p>Before Photo: <Badge text='Missing' /></p><p>After Photo: <Badge text='Uploaded' /></p><p>Notes: <Badge text='Added' /></p></div><button disabled className='mt-4 rounded-xl bg-slate-300 px-4 py-2 text-white'>Mark Completed</button><p className='mt-2 text-red-600 text-sm'>Button disabled until before/after photos are uploaded.</p></div>
    if (path === '/management/sla') return <div className='space-y-5'><h1 className='text-3xl font-bold'>SLA Dashboard</h1><div className='grid gap-4 md:grid-cols-3'><KPI label='SLA Compliance' value='94.2%' /><KPI label='Breaches' value='23' /><KPI label='Aging > 48h' value='14' /></div><div className='grid gap-4 lg:grid-cols-2'><div className={card}><h3 className='text-xl font-semibold'>SLA Compliance Trend</h3><p className='text-sm text-slate-600'>Last 6 months trending between 92%-95%.</p></div><div className={card}><h3 className='text-xl font-semibold'>Breach by Priority</h3><div className='mt-2 flex gap-2'><Badge text='Critical 5'/><Badge text='High 8'/><Badge text='Medium 6'/><Badge text='Low 4'/></div></div></div><FeatureTable title='Drill-down' cols={['Request','Priority','Category','Building','Overdue','Owner']} rows={[['WO-8112','Critical','HVAC','Skyline','2h 20m','PM Sarah']]} /></div>
    return <div className={card}><h1 className='text-3xl font-bold'>Feature Page</h1><p className='mt-2 text-slate-600'>This route has feature-specific placeholder content ready for SRS extension.</p><button onClick={()=>setNote('Action saved and audit logged.')} className='mt-4 rounded-xl bg-[#0B4EDB] px-4 py-2 text-white'>Primary Action</button>{note && <p className='mt-2 text-sm text-emerald-600'>{note}</p>}</div>
  }, [path, note])
  return <AppShell role={role} title={path.split('/').pop()?.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || 'Dashboard'}>{page}</AppShell>
}
