export type RoleKey = 'admin'|'tenant'|'property-manager'|'technician'|'management';
export type SidebarItem = {label:string; path:string};
export type SidebarGroup = {category:string; items:SidebarItem[]};
export type RoleConfig = {name:string; description:string; basePath:string; readOnly:boolean; groups:SidebarGroup[]};
const mk=(items:string[], base:string)=>items.map(i=>({label:i.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),path:`/${base}/${i}`}));
export const ROLE_CONFIG: Record<RoleKey, RoleConfig> = { /* same */
admin:{name:'Admin / Operations',description:'Platform control center',basePath:'admin',readOnly:false,groups:[{category:'Platform Control',items:[{label:'Overview',path:'/admin/overview'},{label:'White Label Settings',path:'/admin/white-label'},{label:'Security Policy',path:'/admin/security'}]},{category:'People & Access',items:[{label:'User Management',path:'/admin/users'},{label:'Tenant Approval Queue',path:'/admin/tenant-approvals'},{label:'Property Managers',path:'/admin/property-managers'},{label:'Technicians',path:'/admin/technicians'}]},{category:'Portfolio Data',items:[{label:'Buildings',path:'/admin/buildings'},{label:'Units',path:'/admin/units'},{label:'Manual Legacy Request Entry',path:'/admin/legacy-entry'}]},{category:'Service Operations',items:[{label:'Service Categories',path:'/admin/service-categories'},{label:'SLA Settings',path:'/admin/sla-settings'},{label:'Notification Providers',path:'/admin/notification-providers'}]},{category:'Governance',items:[{label:'Audit Logs',path:'/admin/audit-logs'},{label:'Report Export Permissions',path:'/admin/export-permissions'}]}]},
tenant:{name:'Tenant / Resident',description:'Resident self-service portal',basePath:'tenant',readOnly:false,groups:[{category:'Account & Access',items:[{label:'Registration',path:'/tenant/register'},{label:'Login / Secure Access',path:'/tenant/login'},{label:'Profile & Unit Information',path:'/tenant/profile'}]},{category:'Maintenance Requests',items:[{label:'Dashboard',path:'/tenant/dashboard'},{label:'My Requests',path:'/tenant/requests'},{label:'Create Maintenance Request',path:'/tenant/create-request'},{label:'Request Details',path:'/tenant/request-details'},{label:'Cancellation Request',path:'/tenant/cancellation-request'},{label:'Reopen Request',path:'/tenant/reopen-request'},{label:'Feedback After Closure',path:'/tenant/feedback'}]},{category:'Communication',items:[{label:'Notification Center',path:'/tenant/notifications'}]},{category:'Smart Portal',items:[{label:'Smart Tenant Portal Insights',path:'/tenant/smart-portal'}]}]},
'property-manager':{name:'Property Manager',description:'Triage and dispatch operations',basePath:'property-manager',readOnly:false,groups:[{category:'Command & Triage',items:mk(['dashboard','new-requests','request-details'],'property-manager')},{category:'Assignment & Tracking',items:mk(['assignment','assigned-tracking','technician-selection','workload-balance'],'property-manager')},{category:'Exceptions & Decisions',items:mk(['cannot-complete','cancellation-decision','reopen-decision','verification'],'property-manager')},{category:'SLA & Reports',items:mk(['sla-breaches','reports'],'property-manager')}]},
technician:{name:'Maintenance Technician',description:'Field execution workspace',basePath:'technician',readOnly:false,groups:[{category:'My Work',items:mk(['tasks','task-details','start-work'],'technician')},{category:'Execution',items:mk(['before-photo','execution-checklist','work-notes','after-photo','mark-completed'],'technician')},{category:'Exceptions',items:mk(['cannot-complete','sla-indicators'],'technician')},{category:'Account & Alerts',items:mk(['location-info','alerts','profile'],'technician')}]},
management:{name:'Management',description:'Executive read-only analytics',basePath:'management',readOnly:true,groups:[{category:'Executive View',items:mk(['executive','sla'],'management')},{category:'Performance Analysis',items:mk(['technician-performance','building-comparison'],'management')},{category:'Reporting',items:mk(['report-export','export-history'],'management')}]},
};
