'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { ROLE_CONFIG, RoleConfig, buildings, techs, workflow } from '@/lib/dashboardData'

const statusCls:any={New:'bg-blue-100 text-blue-700', 'Under Review':'bg-violet-100 text-violet-700', Assigned:'bg-cyan-100 text-cyan-700', 'In Progress':'bg-amber-100 text-amber-700', Completed:'bg-emerald-100 text-emerald-700', Verified:'bg-teal-100 text-teal-700', Closed:'bg-slate-200 text-slate-700', 'Cannot Complete':'bg-red-100 text-red-700', 'Near Breach':'bg-orange-100 text-orange-700', Breached:'bg-red-100 text-red-700', Cancelled:'bg-slate-200 text-slate-700', 'Reopen Requested':'bg-purple-100 text-purple-700'}
export const Badge=({text}:{text:string})=><span className={`px-2 py-1 rounded-full text-xs font-medium ${statusCls[text]||'bg-slate-100'}`}>{text}</span>

function kpis(role:string){return [{label:'Open Requests',value:'128',trend:'+12%',help:'vs last week'},{label:'Near Breach',value:'14',trend:'-3%',help:'needs follow-up'},{label:'Breached',value:'5',trend:'+1',help:'escalated'},{label:'On-time SLA',value:'94.2%',trend:'+2.1%',help:role==='management'?'portfolio wide':'assigned scope'}]}

export function AppShell({role,slug}:{role:RoleConfig;slug:string}){const path=usePathname();
return <div className='min-h-screen bg-slate-100'><div className='sticky top-0 z-20 border-b bg-white/95 backdrop-blur'><div className='mx-auto max-w-[1500px] h-16 px-6 flex items-center justify-between'><div className='font-bold text-2xl'>Smart Maintenance Platform</div><div className='flex gap-3'><select className='border rounded-xl px-3 py-2 text-sm'>{ROLE_CONFIG.map(r=><option key={r.key}>{r.name}</option>)}</select><input className='border rounded-xl px-4 py-2 w-64' placeholder='Search requests, reports, users...' /></div></div></div><div className='mx-auto max-w-[1500px] flex gap-6 p-6'><aside className='w-80 rounded-3xl bg-[#031a36] text-white p-5 h-[calc(100vh-120px)] sticky top-24 overflow-auto'><h2 className='text-2xl font-bold'>{role.name}</h2><p className='text-slate-300 mb-4'>{role.subtitle}</p>{role.groups.map(g=><div key={g.title} className='mb-4'><p className='text-xs uppercase text-slate-400 mb-2'>{g.title}</p><div className='space-y-1'>{g.items.map(i=>{const href=`${role.basePath}/${i.slug}`;const active=path===href;return <Link key={i.slug} href={href} className={`flex items-center gap-2 px-3 py-2 rounded-xl ${active?'bg-white/15 border border-white/20':'hover:bg-white/10'}`}><span>{i.icon}</span><span className='text-sm'>{i.title}</span></Link>})}</div></div>)}</aside><main className='flex-1 space-y-5'>
<div className='rounded-3xl bg-white border p-6 shadow-sm'><p className='text-sm text-slate-500'>Role Context / {role.name}</p><h1 className='text-3xl font-bold'>{role.groups.flatMap(g=>g.items).find(i=>i.slug===slug)?.title}</h1><p className='text-slate-600 mt-1'>SRS workflow visibility: New → Under Review → Assigned → In Progress → Cannot Complete / Completed → Verified → Closed with cancellation, reopen, reassignment and SLA exceptions.</p></div>
<div className='grid lg:grid-cols-4 gap-4'>{kpis(role.key).map(k=><div key={k.label} className='rounded-2xl border bg-white p-4 shadow-sm'><p className='text-sm text-slate-500'>{k.label}</p><p className='text-3xl font-bold'>{k.value}</p><div className='text-xs mt-1 text-emerald-600'>{k.trend} · {k.help}</div></div>)}</div>
<div className='grid lg:grid-cols-3 gap-4'><section className='lg:col-span-2 rounded-2xl border bg-white p-4 shadow-sm'><div className='flex justify-between mb-3'><h3 className='font-semibold'>Operational Queue</h3><div className='flex gap-2'><input className='border rounded-lg px-3 py-1 text-sm' placeholder='Search REQ-1001' /><select className='border rounded-lg px-2 py-1 text-sm'><option>All priorities</option><option>Critical</option><option>High</option></select></div></div><table className='w-full text-sm'><thead><tr className='text-slate-500 border-b'><th className='text-left p-2'>Request</th><th className='text-left p-2'>Building / Unit</th><th className='text-left p-2'>Priority</th><th className='text-left p-2'>Status</th><th className='text-left p-2'>SLA</th></tr></thead><tbody>{[['REQ-1001',`${buildings[0]} / A-1204`,'Critical','Near Breach','00:42'],['REQ-1002',`${buildings[1]} / B-0802`,'High','In Progress','02:12'],['REQ-1003',`${buildings[2]} / C-0311`,'Medium','Cannot Complete','Breached'],['REQ-1004',`${buildings[3]} / A-0901`,'Low','Verified','Closed']].map(r=><tr key={r[0]} className='border-b last:border-0'><td className='p-2 font-medium'>{r[0]}</td><td className='p-2'>{r[1]}</td><td className='p-2'>{r[2]}</td><td className='p-2'><Badge text={r[3]} /></td><td className='p-2'><Badge text={r[4]==='Breached'?'Breached':'Near Breach'} /></td></tr>)}</tbody></table></section>
<section className='rounded-2xl border bg-white p-4 shadow-sm'><h3 className='font-semibold mb-3'>Request Timeline</h3><div className='space-y-3 text-sm'>{[['10:41','Tenant','Request created','New'],['10:52','Manager','Assignment approved','Assigned'],['11:04','Technician','Started field work','In Progress'],['11:31','Technician','Reported blocked valve','Cannot Complete'],['11:45','Manager','Reassigned specialist','Assigned']].map(t=><div key={t[0]} className='border-l-2 pl-3'><p className='text-slate-500'>{t[0]} · {t[1]}</p><p>{t[2]} <Badge text={t[3]} /></p></div>)}</div></section></div>
<div className='grid lg:grid-cols-3 gap-4'><section className='rounded-2xl border bg-white p-4 shadow-sm'><h3 className='font-semibold mb-2'>Evidence & Checklist</h3><p className='text-sm text-slate-600 mb-2'>Before/after photo proof with service narrative and parts used.</p><div className='grid grid-cols-2 gap-2'><div className='h-24 rounded-xl bg-slate-100 grid place-content-center text-xs'>Before Photo</div><div className='h-24 rounded-xl bg-slate-100 grid place-content-center text-xs'>After Photo</div></div></section>
<section className='rounded-2xl border bg-white p-4 shadow-sm'><h3 className='font-semibold mb-2'>Notification Events</h3><ul className='text-sm space-y-2'>{['Request created','Assigned technician update','Cannot complete alert','Completed awaiting verification','Closed confirmation','Cancellation requested','Reopen requested','SLA breach warning'].map(n=><li key={n} className='flex justify-between'><span>{n}</span><Badge text='New' /></li>)}</ul></section>
<section className='rounded-2xl border bg-white p-4 shadow-sm'><h3 className='font-semibold mb-2'>Audit / Export History</h3><ul className='text-sm space-y-1'>{['Admin login success','Tenant approval updated','Attachment uploaded','Status changed to In Progress','Cannot complete submitted','Verification approved','Closure completed','SLA report exported PDF'].map(a=><li key={a} className='text-slate-700'>• {a}</li>)}</ul><p className='text-xs text-slate-500 mt-2'>Assigned techs: {techs.join(', ')}.</p></section></div>
<div className='rounded-2xl border bg-white p-4 shadow-sm'><h3 className='font-semibold mb-3'>Workflow State Model</h3><div className='flex flex-wrap gap-2'>{workflow.map(w=><Badge key={w} text={w} />)}<Badge text='Cancelled'/><Badge text='Reopen Requested'/></div></div>
</main></div></div>
}
