import { AppShell } from '@/components/AppShell'
import { DataTable, FilterBar, KPIStatCard, PageHeader, StatusBadge, card } from '@/components/ModuleUI'

export default function Page(){
  const rows=[['Critical','1h','8h','Plumbing, Electrical, Elevator','24/7','Escalate in 30m','Active'],['High','2h','24h','HVAC, Security','Business Hours','Escalate in 1h','Active'],['Medium','4h','48h','General Maintenance, Cleaning','Business Hours','Escalate in 4h','Active'],['Low','8h','72h','All categories','Business Hours','Daily digest','Active']]
  return <AppShell role='admin' title='SLA Settings'><PageHeader title='SLA Settings' subtitle='Configure response and resolution targets by priority and category.' actions={<button className='rounded-lg bg-[#0B4EDB] px-4 py-2 text-white'>Save Changes</button>} />
  <div className='grid gap-4 md:grid-cols-2 xl:grid-cols-4 mb-5'>{[['Active SLA Rules','12'],['Critical Breach Rate','4.2%'],['Average Response Target','3.8h'],['Average Resolution Target','38h']].map(k=><KPIStatCard key={k[0]} label={k[0]} value={k[1]} />)}</div>
  <DataTable headers={['Priority','Response SLA','Resolution SLA','Applies To Categories','Calendar Mode','Escalation Rule','Status','Actions']} rows={rows.map(r=>[r[0],r[1],r[2],r[3],r[4],r[5],<StatusBadge value={r[6]} key='s'/>,<div key='a' className='flex gap-2'><button>Edit Rule</button><button>Deactivate</button></div>])} />
  <div className='mt-5 grid gap-4 xl:grid-cols-2'><div className={card}><h3 className='font-semibold'>SLA Behavior Settings</h3><ul className='mt-2 text-sm space-y-1 text-slate-600'><li>Response start: <b>New</b> • stop: <b>Assigned</b></li><li>Resolution start: <b>New</b> • stop: <b>Verified</b></li><li>Pause during <b>Cancellation Requested</b></li><li>Continue with flag during <b>Cannot Complete</b></li><li>Reset on <b>Reopen</b></li></ul></div><div className={card}><h3 className='font-semibold'>Category SLA Mapping</h3><div className='mt-2 flex flex-wrap gap-2'>{['Plumbing','Electrical','HVAC','Elevator','General Maintenance'].map(c=><StatusBadge value={c} key={c} />)}</div><p className='mt-3 text-amber-700 text-sm'>Pending client decision: Elevator nighttime escalation policy.</p></div></div></AppShell>
}
